package model.dao;

import model.dto.CastingDirectorDTO;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collection;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class CastingDirectorDAOTest {

    private static CastingDirectorDAO castingDirectorDAO;
    private static JdbcDataSource dataSource;

    // Dummy user IDs created to satisfy the Foreign Key constraint
    private static final int DUMMY_USER_ID = 200;
    private static final int DUMMY_USER_ID_2 = 201;

    @BeforeAll
    static void init() throws SQLException {
        // Setup H2 Database in MySQL compatibility mode
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:testdb_cd;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        castingDirectorDAO = new CastingDirectorDAO(dataSource);

        try (Connection con = dataSource.getConnection();
             Statement stmt = con.createStatement()) {

            stmt.execute("CREATE TABLE User (" +
                    "UserID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "FirstName VARCHAR(50), " +
                    "LastName VARCHAR(50), " +
                    "PasswordHash VARCHAR(255), " +
                    "PhoneNumber CHAR(10), " +
                    "Role VARCHAR(20), " +
                    "Email VARCHAR(100) UNIQUE, " +
                    "RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP" +
                    ");");

            stmt.execute("CREATE TABLE Casting_Director (" +
                    "CdID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "UserID INT NOT NULL, " +
                    "FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE" +
                    ");");

            stmt.execute("INSERT INTO User (UserID, FirstName, LastName, Role, Email) " +
                    "VALUES (" + DUMMY_USER_ID + ", 'Paolo', 'Sorrentino', 'CastingDirector', 'paolo@audire.it')");

            stmt.execute("INSERT INTO User (UserID, FirstName, LastName, Role, Email) " +
                    "VALUES (" + DUMMY_USER_ID_2 + ", 'Martin', 'Scorsese', 'CastingDirector', 'martin@audire.it')");
        }
    }

    @AfterAll
    static void tearDown() throws SQLException {
        // Clean up database
        try (Connection con = dataSource.getConnection();
             Statement stmt = con.createStatement()) {
            stmt.execute("DROP TABLE Casting_Director");
            stmt.execute("DROP TABLE User");
        }
    }

    @Test
    @Order(1)
    void testSaveInsert() throws SQLException {
        CastingDirectorDTO cd = new CastingDirectorDTO();
        cd.setUserID(DUMMY_USER_ID); // Link to the user created in init

        castingDirectorDAO.save(cd);

        assertTrue(cd.getCdID() > 0, "ID (CdID) must be generated by the database after saving.");
        assertEquals(DUMMY_USER_ID, cd.getUserID(), "UserID must match.");
    }

    @Test
    @Order(2)
    void testGetByID() throws SQLException {
        CastingDirectorDTO existing = castingDirectorDAO.getByUserID(DUMMY_USER_ID);
        assertNotNull(existing, "The casting director must exist (created in test 1)");

        CastingDirectorDTO result = castingDirectorDAO.getByID(existing.getCdID());

        assertNotNull(result);
        assertEquals(existing.getCdID(), result.getCdID());
        assertEquals(DUMMY_USER_ID, result.getUserID());
    }

    @Test
    @Order(3)
    void testGetByUserID() throws SQLException {
        CastingDirectorDTO result = castingDirectorDAO.getByUserID(DUMMY_USER_ID);

        assertNotNull(result, "Must find the CD linked to user " + DUMMY_USER_ID);
        assertEquals(DUMMY_USER_ID, result.getUserID());
        assertTrue(result.getCdID() > 0);

        assertNull(castingDirectorDAO.getByUserID(9999), "Must return null for non-existent users");
    }

    @Test
    @Order(4)
    void testGetAll() throws SQLException {
        // Insert a second CD
        CastingDirectorDTO cd2 = new CastingDirectorDTO();
        cd2.setUserID(DUMMY_USER_ID_2);
        castingDirectorDAO.save(cd2);

        Collection<CastingDirectorDTO> list = castingDirectorDAO.getAll(null);

        assertNotNull(list);
        assertTrue(list.size() >= 2, "There should be at least 2 casting directors in the DB.");

        boolean foundFirst = list.stream().anyMatch(cd -> cd.getUserID() == DUMMY_USER_ID);
        boolean foundSecond = list.stream().anyMatch(cd -> cd.getUserID() == DUMMY_USER_ID_2);

        assertTrue(foundFirst && foundSecond, "The list must contain both inserted CDs.");
    }

    @Test
    @Order(5)
    void testDelete() throws SQLException {
        CastingDirectorDTO cd = castingDirectorDAO.getByUserID(DUMMY_USER_ID);
        assertNotNull(cd);

        boolean result = castingDirectorDAO.delete(cd.getCdID());

        assertTrue(result, "Delete must return true if successful.");
        assertNull(castingDirectorDAO.getByID(cd.getCdID()), "The CD must not exist after deletion.");
    }
}