package model.dao;

import model.dto.PerformerDTO;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collection;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PerformerDAOTest {

    private static PerformerDAO performerDAO;
    private static JdbcDataSource dataSource;

    // Constant for the dummy user ID (required for the Foreign Key)
    private static final int DUMMY_USER_ID = 100;

    @BeforeAll
    static void init() throws SQLException {
        // H2 Database setup in MySQL mode
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        performerDAO = new PerformerDAO(dataSource);

        // Schema creation and initial data population
        try (Connection con = dataSource.getConnection();
             Statement stmt = con.createStatement()) {

            // Create User table (Dependency)
            stmt.execute("CREATE TABLE User (" +
                    "UserID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "FirstName VARCHAR(50) NOT NULL, " +
                    "LastName VARCHAR(50) NOT NULL, " +
                    "PasswordHash VARCHAR(255) NOT NULL, " +
                    "PhoneNumber CHAR(10) NOT NULL, " +
                    "Role ENUM('Performer', 'CastingDirector', 'ProductionManager') NOT NULL, " +
                    "Email VARCHAR(100) UNIQUE NOT NULL, " +
                    "RegistrationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP" +
                    ");");

            // Create Performer table
            stmt.execute("CREATE TABLE Performer (" +
                    "PerformerID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "Gender ENUM('M', 'F', 'Altro'), " +
                    "Category ENUM('Attore/Attrice', 'Musicista', 'Cantante', 'Ballerino', 'Doppiatore/trice', 'Qualsiasi') NOT NULL, " +
                    "Description TEXT, " +
                    "CV_Data MEDIUMBLOB, " +
                    "CV_MimeType VARCHAR(255) DEFAULT 'application/pdf', " +
                    "ProfilePhoto VARCHAR(255), " +
                    "UserID INT, " +
                    "FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE" +
                    ");");

            // Insert Dummy User
            String insertUser = "INSERT INTO User (UserID, FirstName, LastName, PasswordHash, PhoneNumber, Role, Email) " +
                    "VALUES (" + DUMMY_USER_ID + ", 'Test', 'User', 'hash123', '3339998877', 'Performer', 'test@audire.it')";
            stmt.execute(insertUser);
        }
    }

    @AfterAll
    static void tearDown() throws SQLException {
        try (Connection con = dataSource.getConnection();
             Statement stmt = con.createStatement()) {
            stmt.execute("DROP TABLE Performer");
            stmt.execute("DROP TABLE User");
        }
    }

    @Test
    @Order(1)
    void testSaveInsert() throws SQLException {
        PerformerDTO newPerformer = new PerformerDTO();
        newPerformer.setUserID(DUMMY_USER_ID);
        newPerformer.setGender(PerformerDTO.Gender.M);
        newPerformer.setCategory(PerformerDTO.Category.Attore_Attrice);
        newPerformer.setDescription("Initial description");
        newPerformer.setProfilePhoto("profile.jpg");
        newPerformer.setCvMimeType("application/pdf");
        newPerformer.setCvData(new byte[]{10, 20, 30}); // Fake binary data

        performerDAO.save(newPerformer);

        assertTrue(newPerformer.getPerformerID() > 0, "ID must be generated by the DB");
    }

    @Test
    @Order(2)
    void testGetByID() throws SQLException {
        // Retrieve the ID generated in the previous step
        PerformerDTO p = performerDAO.getByUserID(DUMMY_USER_ID);
        int realID = p.getPerformerID();

        // Test retrieval by ID
        PerformerDTO result = performerDAO.getByID(realID);
        assertNotNull(result, "Must find the performer with existing ID");
        assertEquals(realID, result.getPerformerID());
        assertEquals("Initial description", result.getDescription());

        // Test non-existent ID
        PerformerDTO notFound = performerDAO.getByID(9999);
        assertNull(notFound, "Must return null if ID does not exist");

        // Test invalid ID
        PerformerDTO invalid = performerDAO.getByID(0);
        assertNull(invalid, "Must return null if ID is 0 or negative");
    }

    @Test
    @Order(3)
    void testGetByUserID() throws SQLException {
        PerformerDTO result = performerDAO.getByUserID(DUMMY_USER_ID);

        assertNotNull(result, "Must find the performer linked to UserID " + DUMMY_USER_ID);
        assertEquals(DUMMY_USER_ID, result.getUserID());
        assertEquals(PerformerDTO.Gender.M, result.getGender());

        PerformerDTO notFound = performerDAO.getByUserID(99999);
        assertNull(notFound, "Must return null if UserID does not have a performer profile");
    }

    @Test
    @Order(4)
    void testSaveUpdate() throws SQLException {
        PerformerDTO existing = performerDAO.getByUserID(DUMMY_USER_ID);
        assertNotNull(existing);

        // Update fields
        existing.setDescription("MODIFIED Description");
        existing.setCategory(PerformerDTO.Category.Cantante);

        // Perform Save (Update)
        performerDAO.save(existing);

        // Verify changes
        PerformerDTO updated = performerDAO.getByID(existing.getPerformerID());
        assertEquals("MODIFIED Description", updated.getDescription());
        assertEquals(PerformerDTO.Category.Cantante, updated.getCategory());
    }

    @Test
    @Order(5)
    void testGetCvData() throws SQLException {
        PerformerDTO p = performerDAO.getByUserID(DUMMY_USER_ID);

        // Retrieve only CV data
        PerformerDTO cvResult = performerDAO.getCvData(p.getPerformerID());

        assertNotNull(cvResult);
        assertNotNull(cvResult.getCvData());
        assertTrue(cvResult.getCvData().length > 0);
        assertEquals("application/pdf", cvResult.getCvMimeType());

        // Ensure other fields are null (optimization check)
        assertNull(cvResult.getDescription());
    }

    @Test
    @Order(6)
    void testGetAll() throws SQLException {
        Collection<PerformerDTO> list = performerDAO.getAll(null);

        assertNotNull(list);
        assertFalse(list.isEmpty());
        assertTrue(list.stream().anyMatch(p -> p.getUserID() == DUMMY_USER_ID));
    }

    @Test
    @Order(7)
    void testDelete() throws SQLException {
        PerformerDTO p = performerDAO.getByUserID(DUMMY_USER_ID);
        int idToDelete = p.getPerformerID();

        boolean deleted = performerDAO.delete(idToDelete);

        assertTrue(deleted, "Delete must return true");
        assertNull(performerDAO.getByID(idToDelete), "Record must be gone after deletion");
    }
}