package model.dao;

import model.dto.ProductionManagerDTO;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collection;

import static org.junit.jupiter.api.Assertions.*;

@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class ProductionManagerDAOTest {

    private static ProductionManagerDAO pmDAO;
    private static JdbcDataSource dataSource;

    // Dummy User IDs for Foreign Key constraints
    private static final int DUMMY_USER_ID_1 = 300;
    private static final int DUMMY_USER_ID_2 = 301;

    @BeforeAll
    static void init() throws SQLException {
        dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:testdb_pm;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        pmDAO = new ProductionManagerDAO(dataSource);

        try (Connection con = dataSource.getConnection();
             Statement stmt = con.createStatement()) {

            stmt.execute("CREATE TABLE User (" +
                    "UserID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "FirstName VARCHAR(50) NOT NULL, " +
                    "LastName VARCHAR(50) NOT NULL, " +
                    "PasswordHash VARCHAR(255) NOT NULL, " +
                    "PhoneNumber CHAR(10) NOT NULL, " +
                    "Role ENUM('Performer', 'CastingDirector', 'ProductionManager') NOT NULL, " +
                    "Email VARCHAR(100) UNIQUE NOT NULL, " +
                    "RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP" +
                    ");");

            stmt.execute("CREATE TABLE Production_Manager (" +
                    "PmID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "UserID INT NOT NULL, " +
                    "FOREIGN KEY (UserID) REFERENCES User(UserID) ON DELETE CASCADE" +
                    ");");

            stmt.execute("INSERT INTO User (UserID, FirstName, LastName, PasswordHash, PhoneNumber, Role, Email) " +
                    "VALUES (" + DUMMY_USER_ID_1 + ", 'Quentin', 'Tarantino', 'hash123', '3330000001', 'ProductionManager', 'quentin@audire.it')");

            stmt.execute("INSERT INTO User (UserID, FirstName, LastName, PasswordHash, PhoneNumber, Role, Email) " +
                    "VALUES (" + DUMMY_USER_ID_2 + ", 'Christopher', 'Nolan', 'hash456', '3330000002', 'ProductionManager', 'nolan@audire.it')");
        }
    }

    @AfterAll
    static void tearDown() throws SQLException {
        // Clean up database
        try (Connection con = dataSource.getConnection();
             Statement stmt = con.createStatement()) {
            stmt.execute("DROP TABLE Production_Manager");
            stmt.execute("DROP TABLE User");
        }
    }

    @Test
    @Order(1)
    void testSaveInsert() throws SQLException {
        ProductionManagerDTO pm = new ProductionManagerDTO();
        pm.setUserID(DUMMY_USER_ID_1);

        pmDAO.save(pm);

        assertTrue(pm.getPmID() > 0, "ID (PmID) must be generated by the database after saving.");
        assertEquals(DUMMY_USER_ID_1, pm.getUserID(), "UserID must match.");
    }

    @Test
    @Order(2)
    void testGetByID() throws SQLException {
        ProductionManagerDTO existing = pmDAO.getByUserID(DUMMY_USER_ID_1);
        assertNotNull(existing, "PM must exist (created in test 1)");

        ProductionManagerDTO result = pmDAO.getByID(existing.getPmID());

        assertNotNull(result);
        assertEquals(existing.getPmID(), result.getPmID());
        assertEquals(DUMMY_USER_ID_1, result.getUserID());

        assertNull(pmDAO.getByID(99999), "Must return null for non-existent IDs");
    }

    @Test
    @Order(3)
    void testGetByUserID() throws SQLException {
        ProductionManagerDTO result = pmDAO.getByUserID(DUMMY_USER_ID_1);

        assertNotNull(result, "Must find the PM linked to user " + DUMMY_USER_ID_1);
        assertEquals(DUMMY_USER_ID_1, result.getUserID());
        assertTrue(result.getPmID() > 0);

        assertNull(pmDAO.getByUserID(9999), "Must return null for non-existent users");
    }

    @Test
    @Order(4)
    void testGetAll() throws SQLException {
        // Insert a second PM
        ProductionManagerDTO pm2 = new ProductionManagerDTO();
        pm2.setUserID(DUMMY_USER_ID_2);
        pmDAO.save(pm2);

        Collection<ProductionManagerDTO> list = pmDAO.getAll(null);

        assertNotNull(list);
        assertTrue(list.size() >= 2, "There should be at least 2 production managers in the DB.");

        boolean foundFirst = list.stream().anyMatch(pm -> pm.getUserID() == DUMMY_USER_ID_1);
        boolean foundSecond = list.stream().anyMatch(pm -> pm.getUserID() == DUMMY_USER_ID_2);

        assertTrue(foundFirst && foundSecond, "The list must contain both inserted PMs.");
    }

    @Test
    @Order(5)
    void testDelete() throws SQLException {
        ProductionManagerDTO pm = pmDAO.getByUserID(DUMMY_USER_ID_1);
        assertNotNull(pm);

        boolean result = pmDAO.delete(pm.getPmID());

        assertTrue(result, "Delete must return true if successful.");
        assertNull(pmDAO.getByID(pm.getPmID()), "PM must not exist after deletion.");

        assertFalse(pmDAO.delete(pm.getPmID()), "Delete on an already deleted record must return false");
    }

}